spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/autosalons?stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

jwt:
  secret: Y2mEHclUKTnwfxT9V+0YECgdn8r7Ieryk2e7IraH8k0=
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
