DROP TABLE IF EXISTS cars_reviews CASCADE;
DROP TABLE IF EXISTS persons_contacts CASCADE;
DROP TABLE IF EXISTS autosalons_contacts CASCADE;
DROP TABLE IF EXISTS dealers_contacts CASCADE;
DROP TABLE IF EXISTS dealers_cars CASCADE;
DROP TABLE IF EXISTS dealers_reviews CASCADE;
DROP TABLE IF EXISTS autosalons_cars CASCADE;
DROP TABLE IF EXISTS autosalons_reviews CASCADE;

DROP TABLE IF EXISTS test_drives CASCADE;
DROP TABLE IF EXISTS sales CASCADE;
DROP TABLE IF EXISTS contacts CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS cars CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS persons CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS dealers CASCADE;
DROP TABLE IF EXISTS autosalons CASCADE;
DROP TABLE IF EXISTS addresses CASCADE;

DROP TYPE IF EXISTS contact_type_enum CASCADE;
DROP TYPE IF EXISTS role_enum CASCADE;
